/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mx.itson.potromon.ui;

import java.util.List;
import javax.swing.JOptionPane;
import mx.itson.potromon.entidades.Entrenador;
import mx.itson.potromon.entidades.Potrodex;

/**
 * Clase que representa un formulario para registrar o editar un Potromon.
 * Esta clase extiende JDialog y permite al usuario ingresar información sobre un Potromon.
 * 
 * @author emili
*/
public class PotrodexForm extends javax.swing.JDialog {
    
    int idPotrodex;
    /**
     * Crea una nueva instancia de PotrodexForm.
     * 
     * @param parent El marco padre del diálogo.
     * @param modal Indica si el diálogo es modal.
     * @param idPotrodex El ID del Potromon a editar, si es mayor que 0.
     */
    public PotrodexForm(java.awt.Frame parent, boolean modal, int idPotrodex) {
        super(parent, modal);
        initComponents();
        this.idPotrodex = idPotrodex;
        
        // Carga la información del Potromon si el ID es mayor que 0
        if (idPotrodex > 0) {
            Potrodex potrodex = Potrodex.getById(idPotrodex);
            if (potrodex != null) {
                txtNombre.setText(potrodex.getNombrePotromon());
                txtDescripcion.setText(potrodex.getDescripcion());
                txtPoderes.setText(potrodex.getPoderes());
                txtPuntaje.setText(String.valueOf(potrodex.getPuntaje()));
                // Se puede cargar el entrenador aquí si es necesario
                //cmbEntrenador.
            }
        }
        // Carga los entrenadores en un hilo separado
                Thread thread = new Thread( () -> {
                
       cargarEntrenadores();
        
        });
        thread.start();
        
}        
        
        
    /**
    * Carga la lista de entrenadores en el combo box.
    */    
    
    public void cargarEntrenadores() {
    List <Entrenador> entrenadores = Entrenador.getAll();
    for (Entrenador e : entrenadores){
        cmbEntrenador.addItem(e);
        
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcion = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPuntaje = new java.awt.TextField();
        btnAceptar = new javax.swing.JButton();
        cmbEntrenador = new javax.swing.JComboBox<>();
        btnHabilidades = new javax.swing.JButton();
        txtImagen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fondoo = new javax.swing.JLabel();
        lblPoderes = new javax.swing.JLabel();
        txtPoderes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre:");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 127, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("REGISTRO POTROMON");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 258, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Descripcion (Breve)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 207, 27));

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 258, 49));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Habilidades:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Puntaje:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        txtPuntaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPuntajeActionPerformed(evt);
            }
        });
        getContentPane().add(txtPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 170, 30));

        btnAceptar.setBackground(new java.awt.Color(204, 0, 0));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, 130, 40));

        cmbEntrenador.setBackground(new java.awt.Color(255, 255, 255));
        cmbEntrenador.setForeground(new java.awt.Color(0, 0, 0));
        cmbEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEntrenadorActionPerformed(evt);
            }
        });
        getContentPane().add(cmbEntrenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 119, -1));

        btnHabilidades.setBackground(new java.awt.Color(255, 255, 255));
        btnHabilidades.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        btnHabilidades.setForeground(new java.awt.Color(0, 0, 0));
        btnHabilidades.setText("Habilidades");
        btnHabilidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilidadesActionPerformed(evt);
            }
        });
        getContentPane().add(btnHabilidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 420, 40));

        txtImagen.setBackground(new java.awt.Color(255, 255, 255));
        txtImagen.setForeground(new java.awt.Color(0, 0, 0));
        txtImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImagenActionPerformed(evt);
            }
        });
        getContentPane().add(txtImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 300, -1));

        jLabel6.setText("URL imagen");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        jLabel7.setText("Entrenador");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, -1, -1));

        fondoo.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.ibb.co/WV7wJCb/fondopokebola.jpg")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        fondoo.setText("jLabel7");
        getContentPane().add(fondoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 660));

        lblPoderes.setText("jLabel8");
        getContentPane().add(lblPoderes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));
        getContentPane().add(txtPoderes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEntrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEntrenadorActionPerformed

    private void txtImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImagenActionPerformed

    private void txtPuntajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuntajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuntajeActionPerformed
    /**
     * Maneja el evento de acción del botón "Aceptar".
     * Este método guarda o edita la información del Potromon según el ID.
     * 
     * @param evt El evento de acción que se genera al presionar el botón.
     */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String nombre = txtNombre.getText();
        String descripcion = txtDescripcion.getText();
        String poderes = txtPoderes.getText();
        String Imagen = txtImagen.getText();
        int puntaje = Integer.parseInt(txtPuntaje.getText());

        Entrenador entrenadorSeleccionado = (Entrenador) cmbEntrenador.getSelectedItem();
        if (entrenadorSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un responsable.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Potrodex potrodex = new Potrodex();
        potrodex.setEntrenador(entrenadorSeleccionado);

        boolean resultado = this.idPotrodex == 0 ?
        Potrodex.save(nombre, descripcion, poderes, puntaje, Imagen, entrenadorSeleccionado):
        Potrodex.edit(idPotrodex, nombre, descripcion, poderes, puntaje, Imagen, entrenadorSeleccionado);
        if(resultado){
            JOptionPane.showMessageDialog (this,"El registro se guardo correctamente", "Registro guardado",JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }else {
            JOptionPane.showMessageDialog (this,"El registro tuvo un error al guardar" , "Error al guardar",JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed
    /**
     * Maneja el evento de acción del botón "Habilidades".
     * Este método puede abrir un formulario para gestionar las habilidades del Potromon.
     * 
     * @param evt El evento de acción que se genera al presionar el botón.
     */
    private void btnHabilidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilidadesActionPerformed
       //HabilidadesForm form = new HabilidadesForm(this, true, 0);
       //form.setVisible(true);
    }//GEN-LAST:event_btnHabilidadesActionPerformed

    /**
     * Método principal que inicia la aplicación y muestra el diálogo de PotrodexForm.
     * 
     * @param args Los argumentos de línea de comandos.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PotrodexForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PotrodexForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PotrodexForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PotrodexForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Crea y muestra el diálogo 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PotrodexForm dialog = new PotrodexForm(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);  //Cierra la aplicación al cerrar el diálogo
                    }
                });
                dialog.setVisible(true); // Muestra el diálogo
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnHabilidades;
    private javax.swing.JComboBox<Entrenador> cmbEntrenador;
    private javax.swing.JLabel fondoo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblPoderes;
    private java.awt.TextField txtDescripcion;
    private javax.swing.JTextField txtImagen;
    private java.awt.TextField txtNombre;
    private javax.swing.JTextField txtPoderes;
    private java.awt.TextField txtPuntaje;
    // End of variables declaration//GEN-END:variables
}
